version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: ferretera-db-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ferretera-backend-prod
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: ${SECRET_KEY}
      CORS_ORIGINS: '["https://ferreteria-village.com"]'
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ferretera-frontend-prod
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: https://api.ferreteria-village.com/api/v1
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata_prod:
    driver: local